### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by pinjaw** [msiivone/epsilan-ry-kotisivut#2]
Hei!
Työ on mukavan laaja ja tuntuu että sovelluksessa on hyvin erilaisia ja monipuolisia toimintoja. Kokeilin tässä maanantaiaamuna käyttää sovellusta ja tein sinne uuden tilin sekä kokeilin käyttää sovellusta annetulla moderaattoritunnuksella. Käyttökokemus oli todella sulava ja en ainakaan heti löytänyt mitään bugeja, mihin sovellus olisi kaatunut tai vastannut huonosti. Käytettävyys oli  siis yleisesti hyvä ja oli selkeää mitä mikäkin toiminto teki. Sivut olivat myös hauskat ja persoonalliset.
Kerta mahdollisuus oli annettu, kokeilin antaa porttikiellon käyttäjälle "käyttäjä", joten toivottavasti tämä ei aiheuttanut ongelmia, jos sovellus on tulossa oikeasti kaveriporukan käyttöön. Toivottavasti saat poistettua kaiken mitä lisäsin sovellukseen, jos niitä ei haluta mukaan :)
Oli hieman hassua, että porttikiellon antamiselle oli oma painike päävalikossa, sillä luulisi että se ei ole toiminto, jota tulee käytettyä usein. Toki tämä voi olla tietoinen valinta, mutta tuli vain mieleen, että porttikiellon antaminen on ehkä toiminto, jonka voisi piilottaa jonnekkin paremmin. Ellei sitten porttikieltoja oikeasti anneta erittäin usein, mistäs sitä tietää.
Koodi näytti metoditasolla yleisesti hyvältä ja selkeältä, samoin sivupohjat. Hassu asia oli vain se, että koko sovellus on yhdessä pitkässä python-tiedostossa. Kannataisi varmaan jakaa koodi omiin moduuleihin, niin se voisi selkeyttää tekstiä entisestään.
Yleisesti  työ vaikutti oikein hyvältä. Onnea vielä loppupalautukseen!

**Comment by pinjaw** [comment]
Hupsis! Huomasin vasta nyt, että tuossa README:ssä oli annettu myös normaalin käyttäjän tunnukset ja annoin sitten bännit tälle käyttäjätunnukselle. Pahoittelut tästä, toivottavasti saat korjattua homman :"D

**Comment by msiivone** [comment]
Eipä mitään. Otin sen bannit pois jo tossa maanantaina päivällä. Kiitos hyvästä palautteesta! :)
